name: Terraform Apply

on:
  workflow_dispatch: # ręczne uruchomienie z UI

jobs:
  apply:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      deployments: write

    environment: production

    env:
      AWS_REGION: eu-north-1

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Configure AWS credentials (Assume Apply Role)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/terraform_apply_role
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform init
        run: terraform init -upgrade

      - name: Download plan artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: .

      - name: Terraform apply (from plan)
        run: terraform apply -auto-approve tfplan.binary